import { Project, PMO, ProductManager } from '../types'

export const mockPMOs: PMO[] = [
  { id: 'pmo-1', name: 'PMO-A', enabled: true },
  { id: 'pmo-2', name: 'PMO-B', enabled: true },
  { id: 'pmo-3', name: 'PMO-C', enabled: true },
  { id: 'pmo-4', name: 'PMO-D', enabled: true },
  { id: 'pmo-5', name: 'PMO-E', enabled: true },
]

export const mockProductManagers: ProductManager[] = [
  { id: 'pm-1', name: '产品经理A', enabled: true },
  { id: 'pm-2', name: '产品经理B', enabled: true },
  { id: 'pm-3', name: '产品经理C', enabled: true },
  { id: 'pm-4', name: '产品经理D', enabled: true },
  { id: 'pm-5', name: '产品经理E', enabled: true },
]

export const mockProjects: Project[] = [
  {
    id: '1',
    name: '短剧小程序',
    status: 'normal',
    progress: 75,
    startDate: '2026-01-01',
    endDate: '2026-02-15',
    partners: ['360金条'],
    developers: ['张三', '李四'],
    testers: ['王五', '赵六'],
    owner: '项目经理A',
    productManager: '产品经理A',
    pmo: 'PMO-A',
    remark: '重点项目，需按时上线',
  },
  {
    id: '2',
    name: '支付中台改造',
    status: 'delayed',
    progress: 45,
    startDate: '2025-12-15',
    endDate: '2026-01-20',
    partners: ['支付宝', '微信支付'],
    developers: ['王靖博', '邓晓旭'],
    testers: ['史宁博'],
    owner: '项目经理B',
    productManager: '产品经理B',
    pmo: 'PMO-B',
    remark: '存在技术难点，需要协调资源',
  },
  {
    id: '3',
    name: '用户中心升级',
    status: 'risk',
    progress: 60,
    startDate: '2026-01-05',
    endDate: '2026-02-10',
    partners: ['内部系统'],
    developers: ['陈七', '周八'],
    testers: ['吴九', '郑十'],
    owner: '项目经理C',
    productManager: '产品经理C',
    pmo: 'PMO-C',
    remark: '依赖外部接口，存在风险',
  },
  {
    id: '4',
    name: '数据报表系统',
    status: 'normal',
    progress: 30,
    startDate: '2026-01-20',
    endDate: '2026-03-15',
    partners: ['BI部门'],
    developers: ['孙十一'],
    testers: ['钱十二'],
    owner: '项目经理D',
    productManager: '产品经理D',
    pmo: 'PMO-D',
  },
  {
    id: '5',
    name: '营销活动平台',
    status: 'pending',
    progress: 0,
    startDate: '2026-02-01',
    endDate: '2026-03-30',
    partners: ['市场部'],
    developers: ['李十三'],
    testers: ['王十四'],
    owner: '项目经理E',
    productManager: '产品经理E',
    pmo: 'PMO-E',
  },
]